### PR TITLE
fix(github-action):  build action failing

### PR DESCRIPTION
**Pull request by Ab-hishek**
**Why is this PR required? What issue does it fix?**:
This PR fixes the build action failing issue.

**What this PR does?**:
Build gitHub action were failing because specific go packages are available only in `go1.16` version and by default `ubuntu-latest` image used in the action uses `go1.15.15` version. Hence, some packages were not found.

The fixes that this PR introduces are:
1. Add go-setup action in the build, pull_request and release gitHub actions workflows.
2. It also removes all the references to `Ab-hishek`'s gtihub data-populator code.
3. Add missing license headers in the v1alpha1 packages files.
4. Add missing makefile targets.
5. Updates the go mod module name.
6. update default credentials used in the rsync-daemon image.
7. Change all image names to `openebs` registries.
8. Makes `rsync-daemon` image name configurable in data-populator.

**Does this PR require any upgrade changes?**:
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Fixes #<issue number>
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

**Comment by Ab-hishek** [comment]
@pawanpraka1 Why are the docker build action being skipped?

**Comment by Ab-hishek** [comment]
@pawanpraka1 @kmova The image builds are failing saying `docker hub username and password required`.

**Comment by pawanpraka1** [comment]
@Ab-hishek in pull request, we should not be pushing any images. Images should be push in build and release gitaction only. We should not even try to login to Docker hub in pull request action.

**Comment by Ab-hishek** [comment]
Resolved that @pawanpraka1 . But still docker says authorisation failed.

**Comment by pawanpraka1** [comment]
@Ab-hishek you need to make push: false to not try to push it. Can you check how we are doing in lvm-localpv here https://github.com/openebs/lvm-localpv/blob/develop/.github/workflows/pull_request.yml.

**Review by pawanpraka1 — APPROVED** [review]
looks good.

**Comment by pawanpraka1** [comment]
@Ab-hishek can you check why build action is failing. Also check the release action for any error.

**Comment by Ab-hishek** [comment]
@pawanpraka1 We need to create data-populator repository in `quay`. In `quay` if the repository is not already present, it throws error. Since, data-populator is new hence we need to create on. I don't the credentials for quay. Can you provide me or create it yourself?

**Comment by pawanpraka1** [comment]
@kmova can you create a quay repository for data-populator? Also I remember we need to make docker image public, can you check and do the necessary setup for this repo.

**Pull request merged**
