### PR TITLE
add github action workflow and license, update makefile and READMEs

### PR DESCRIPTION
**Pull request by Ab-hishek**
## What this PR does?

This PR:
1. adds GitHub action workflows for build, pull request and release.
2. Updated makefile changes to incorporate openebs related image registry changes(i.e building images in correct openebs registry locations)
3. Updates existing READMEs as well as adds new READMEs for contribution guides, code of conduct, guidance, maintainers.
4. Add templates for raising issues as well as feature-requests.

### CODE REVIEW

**Comment by pawanpraka1** [comment]
@Ab-hishek can you check the comments from lift app and fix them?

**Comment by pawanpraka1** [comment]
@kmova can you add all the github envs for this repo?

**Comment by kmova** [comment]
@pawanpraka1 -- Done

**Review by pawanpraka1 — APPROVED** [review]
looks good.

**Comment by pawanpraka1** [comment]
@Ab-hishek github action failed. Can you please take a look.

**Pull request merged**
